### ISSUE TITLE
Missing addComponent and getComponent types

### ISSUE THREAD

**Issue by jjhii** [Kyle-Muir/bing-maps-ajax-control-typescript-declaration#1]
When adding the following I get an error on missing addComponent and getComponent function.

map.addComponent('searchManager', new Microsoft.Maps.Search.SearchManager(map)); 
searchManager = map.getComponent('searchManager'); 
displayAlert('Search module loaded'); 

I added the following to the Microsoft.Maps.d.ts map class.

addComponent(searchId: string, searchManager: Microsoft.Maps.Search.SearchManager): void;
getComponent(searchId: string): Microsoft.Maps.Search.SearchManager;

Not sure if that is correct but it seems to get rid of the error.  Might supposed to be any instead of SearchManager.

**Comment by Kyle-Muir** [comment]
Hi John,

I've had a look into the Bing Maps API (https://msdn.microsoft.com/en-us/library/gg427610.aspx) and can't see this method at all? Can you find any documentation for me? 

I've found various examples online using these two methods purely for adding\loading searchManager but I imagine it could be used for other things. It would be good to know what those are before adding in a fix.

Cheers,

Kyle

**Comment by Kyle-Muir** [comment]
I have added these checks in, now pending an update to nuget. I have left it as:

```
addComponent(componentName: string, component: any);
getComponent(componentName: string): any;
```

However, in your code you can cast it to whatever you want to gain better intellisense, e.g.:

```
var searchManager: Microsoft.Maps.Search.SearchManager = map.getComponent('searchManager');
searchManager.search(...)
```

I will attempt to release an update to nuget later on today (NZDT).

Once I've released it I will close this issue.

**Comment by Kyle-Muir** [comment]
Deployed update to Nuget, new package can be found here: https://www.nuget.org/packages/BingMapsTypeScript/1.0.5
