### ISSUE TITLE
Bing Maps V8 TypeScript definitions

### ISSUE THREAD

**Issue by rbrundritt** [Kyle-Muir/bing-maps-ajax-control-typescript-declaration#2]
I want to say thank you for putting these together for the Bing Maps V7 control. I always thought that the Bing Maps team really should have made these available, but unfortunately the dev team didn't. But it is great to see that the community didn't let that stop them. 

I am the Bing Maps program manager who is leading the development of the Bing Maps V8 map control. This project helped me show the dev team that our developer community wants TypeScript support. This was a fairly easy case to make as we used TypeScript to develop V8.

With that we have created a GitHub project for [Bing Maps V8 TypeScript definitions](https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions). These are updated usually the week before a release/update announcement by the V8 dev team and myself. 

I would like to personally invite you to contribute to this project as you see fit. If you feel that this project is up to your standards, I would greatly appreciate it if you also provided a link to it from your project. 

Thank you again for your contribution to the Bing Maps developer community.
Ricky Brundritt

**Comment by Kyle-Muir** [comment]
Hi Ricky,

Thank you for your kind words. Link has now been added and I am happy to leave the definition files to the experts :)

Happy to have been a stop gap measure for people who were looking for these definitions.

Thanks,

Kyle

**Comment by rbrundritt** [comment]
Great, Thanks.
